name: github-action
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: action/checkout@v2
      -uses: action/setup-node@v1
      -run: npm install
      -run: make lint
      -run: npm test

