name: github-action

on: push

env:
  CI: true

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      -uses: action/checkout@v2

      -name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

      -run: npm install

      -run: make lint

      -run: make test

